apiVersion: kfn.dajac.io/v1alpha1
kind: Function
metadata:
  name: copy-function
spec:
  replicas: 1
  image: dajac/kfn-examples:0.1.0
  class: io.dajac.kfn.examples.CopyFunction
  
  input: kfn.source
  inputKeyDeserializer: bytes
  inputValueDeserializer: bytes
  
  output: kfn.destination
  outputKeySerializer: bytes
  outputValueSerializer: bytes
